### PR TITLE
Fix: Fix keepspaces option to work with nested lists

### LINKED ISSUE #119: keepspaces doesn't work with nested list items.
## Bug

The `$keepspaces=1` option ("Clear double spaces in bullets") only works for top-level list items, not nested list items.

## Expectation

It should work for nested list items too.

## Discussion

If you have a note like:
image

The generated markdown is:
```
-   List item 1

    -   Nested item 1

    -   Nested item 2
-   List item 2
```

But it should ideally be:
```
-   List item 1
    -   Nested item 1
    -   Nested item 2
-   List item 2
```

I'll send a PR that fixes this.

## Environment

**Output of Configuration**

```powershell
Configuration:
dryRun: 1
notesdestpath: d:\drive\docs\Obsidian\Life
targetNotebook: MigrationTest
usedocx: 1
keepdocx: 2
docxNamingConvention: 2
prefixFolders: 1
mdFileNameAndFolderNameMaxLength: 255
medialocation: 2
conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_tables
headerTimestampEnabled: 1
keepspaces: 1
keepescape: 1
newlineCharacter: 1
exportPdf: 1```

**Output of `$PSVersionTable`**

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by mikelehen**
Fixes #119.

### CODE REVIEW

**Comment by nixsee** [comment]
Nice one. I am the original creator of this tool but no longer the maintainer... I hope that @theohbrothers2 @leojonathanoh @joeltimothyoh are still around in some form!

**Comment by leojonathanoh** [comment]
@nixsee i've managed to get some time to fix this. :P

**Comment by leojonathanoh** [comment]
lgtm, thanks @mikelehen!

**Comment by mikelehen** [comment]
@leojonathanoh Thanks so much!  🙏

**Pull request merged**
